### PR TITLE
added endpoint to enable localstack

### PR DESCRIPTION
**Pull request by ornmikael**
need to be able to set endpoint for localstack

### CODE REVIEW

**Comment by ornmikael** [comment]
@martaver tested this locally and seems to work. but im unsure if its sound typescript. heard you were the expert

**Comment by martaver** [comment]
As per discussion in slack, endpoints configured at per-service level is best.

Outstanding:
- [ ] Remove accidental package-lock.json (we use yarn, not npm)
- [ ] Check that default settings configured in `AWS.config` (such as `region`) are still applied to services which accept the `endpoint` property in their constructor. In other words, make sure you aren't overwriting the default configuration for instances that aren't using localstack, because that will be a breaking change (and a bug)

**Comment by ornmikael** [comment]
@martaver tested with and without endpoint and works fine

**Comment by martaver** [comment]
lgtm!

**Pull request merged**
